objects/Asset.object
<CustomObject>
    <fields>
        <fullName>End_Date_Text__c</fullName>
        <formula>TEXT(MONTH(UsageEndDate)) + &apos;/&apos; + TEXT(DAY(UsageEndDate)) + &apos;/&apos; + TEXT(YEAR(UsageEndDate))</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>End Date Text</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Kiosk__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Location (LIN)</label>
        <referenceTo>Kiosk__c</referenceTo>
        <relationshipLabel>Bookings</relationshipLabel>
        <relationshipName>Assets</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Start_Date_Text__c</fullName>
        <formula>TEXT(MONTH(InstallDate)) + &apos;/&apos; + TEXT(DAY(InstallDate)) + &apos;/&apos; + TEXT(YEAR(InstallDate))</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Start Date Text</label>
        <type>Text</type>
    </fields>
</CustomObject>

objects/Date_Input__c.object
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <fields>
        <fullName>Date_Field_1__c</fullName>
        <label>Date Field 1</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Date_Field_2__c</fullName>
        <label>Date Field 2</label>
        <type>Date</type>
    </fields>
    <label>Date Input</label>
</CustomObject>

objects/Kiosk__c.object
<CustomObject>
    <description>Location ID, formerly &quot;The kiosks associated with a specific location&quot; however we are now splitting the apart. What was the KIN is now the LIN, which represents the location of the charging station.</description>
    <fields>
        <fullName>Charging_Engineered_for__c</fullName>
        <description>This tracks the charing level the site was engineered for. The amperage made available to the Location (LIN) via the make-ready. Should be tested to always be a lower value than the output of the line loss equation.</description>
        <inlineHelpText>This tracks the charing level the site was engineered for. The amperage made available to the Location (LIN) via the make-ready. Should be tested to always be a lower value than the output of the line loss equation.</inlineHelpText>
        <label>Charging Engineered for</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Standard_Amperage</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>City__c</fullName>
        <label>City</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Latitude__c</fullName>
        <label>Latitude</label>
        <precision>18</precision>
        <scale>9</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Longitude__c</fullName>
        <label>Longitude</label>
        <precision>18</precision>
        <scale>9</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Network_Region__c</fullName>
        <label>Network Region</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>CA - Northern</fullName>
                </value>
                <value>
                    <fullName>CA - Santa Barbara</fullName>
                </value>
                <value>
                    <fullName>CA - Los Angeles</fullName>
                </value>
                <value>
                    <fullName>CA - Orange County</fullName>
                </value>
                <value>
                    <fullName>CA - San Diego</fullName>
                </value>
                <value>
                    <fullName>HI</fullName>
                </value>
                <value>
                    <fullName>AZ</fullName>
                </value>
                <value>
                    <fullName>FL</fullName>
                </value>
                <value>
                    <fullName>Chicago</fullName>
                </value>
                <value>
                    <fullName>DC</fullName>
                </value>
                <value>
                    <fullName>NJ</fullName>
                </value>
                <value>
                    <fullName>NY</fullName>
                </value>
                <value>
                    <fullName>Oregon</fullName>
                </value>
                <value>
                    <fullName>Texas</fullName>
                </value>
                <value>
                    <fullName>Seattle</fullName>
                </value>
                <value>
                    <fullName>Boston</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>State__c</fullName>
        <label>State</label>
        <length>2</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Initial Site Inspection</fullName>
                    <color>#F96FB7</color>
                    <label>Initial Site Inspection</label>
                </value>
                <value>
                    <fullName>Under Construction</fullName>
                    <color>#FFFF66</color>
                    <label>Under Construction</label>
                </value>
                <value>
                    <fullName>Active</fullName>
                    <color>#78C953</color>
                    <label>Active</label>
                </value>
                <value>
                    <fullName>Needs Service</fullName>
                    <color>#FF0000</color>
                    <label>Needs Service</label>
                </value>
                <value>
                    <fullName>Decommissioned - Out of Service</fullName>
                    <color>#333333</color>
                    <label>Decommissioned - Out of Service</label>
                </value>
                <value>
                    <fullName>Disqualified</fullName>
                    <color>#E27001</color>
                    <label>Disqualified</label>
                </value>
                <value>
                    <fullName>On Hold - Muni Obstacles</fullName>
                    <color>#8F6429</color>
                    <label>On Hold - Muni Obstacles</label>
                </value>
                <value>
                    <fullName>On Hold - Property Ownership</fullName>
                    <color>#AFCADF</color>
                    <label>On Hold - Property Ownership</label>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Street_Address__c</fullName>
        <label>Street Address</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Zip_Code__c</fullName>
        <label>Zip Code</label>
        <length>9</length>
        <type>Text</type>
    </fields>
    <label>Location (LIN)</label>
    <nameField>
        <label>Location Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Locations (LIN)</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Opportunity.object
<CustomObject>
    <fields>
        <fullName>City__c</fullName>
        <label>City</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Network_Region__c</fullName>
        <description>Network location (Region) that links to the appropriate network code.</description>
        <label>Network (Region)</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Hawaii</fullName>
                </value>
                <value>
                    <fullName>North CA</fullName>
                </value>
                <value>
                    <fullName>Los Angeles</fullName>
                </value>
                <value>
                    <fullName>Orange County</fullName>
                </value>
                <value>
                    <fullName>Santa Barbara</fullName>
                </value>
                <value>
                    <fullName>San Diego</fullName>
                </value>
                <value>
                    <fullName>Arizona</fullName>
                </value>
                <value>
                    <fullName>South FL</fullName>
                </value>
                <value>
                    <fullName>Chicago</fullName>
                </value>
                <value>
                    <fullName>Portland</fullName>
                </value>
                <value>
                    <fullName>Washington DC</fullName>
                </value>
                <value>
                    <fullName>New Jersey</fullName>
                </value>
                <value>
                    <fullName>New York</fullName>
                </value>
                <value>
                    <fullName>Seattle</fullName>
                </value>
                <value>
                    <fullName>Pennsylvania</fullName>
                </value>
                <value>
                    <fullName>Ohio</fullName>
                </value>
                <value>
                    <fullName>Kentucky</fullName>
                </value>
                <value>
                    <fullName>Connecticut</fullName>
                </value>
                <value>
                    <fullName>Utah</fullName>
                </value>
                <value>
                    <fullName>Colorado</fullName>
                </value>
                <value>
                    <fullName>Texas</fullName>
                </value>
                <value>
                    <fullName>Atlanta</fullName>
                </value>
                <value>
                    <fullName>Baltimore</fullName>
                </value>
                <value>
                    <fullName>South</fullName>
                </value>
                <value>
                    <fullName>Other</fullName>
                </value>
                <value>
                    <fullName>New England</fullName>
                </value>
                <value>
                    <fullName>Middle Atlantic</fullName>
                </value>
                <value>
                    <fullName>East North Central</fullName>
                </value>
                <value>
                    <fullName>West North Central</fullName>
                </value>
                <value>
                    <fullName>South Atlantic</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>State__c</fullName>
        <label>State</label>
        <length>2</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Zip_Code__c</fullName>
        <label>Zip Code</label>
        <length>5</length>
        <type>Text</type>
    </fields>
</CustomObject>

objects/Product2.object
<CustomObject>
    <fields>
        <fullName>Kiosk__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Location</label>
        <referenceTo>Kiosk__c</referenceTo>
        <relationshipLabel>Face</relationshipLabel>
        <relationshipName>Products</relationshipName>
        <type>Lookup</type>
    </fields>
</CustomObject>

objects/Quote.object
<CustomObject>
    <fields>
        <fullName>End_Date_for_Map_Page__c</fullName>
        <label>End Date for Map Page</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Start_Date_for_Map_Page__c</fullName>
        <label>Start Date for Map Page</label>
        <type>Date</type>
    </fields>
</CustomObject>

objects/QuoteLineItem.object
<CustomObject>
    <fields>
        <fullName>End_Date_Text__c</fullName>
        <formula>TEXT(MONTH(End_Date__c)) + &apos;/&apos; + TEXT(DAY(End_Date__c)) + &apos;/&apos; + TEXT(YEAR(End_Date__c))</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>End Date Text</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>End_Date__c</fullName>
        <label>End Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Start_Date_Text__c</fullName>
        <formula>TEXT(MONTH(Start_Date__c)) + &apos;/&apos; + TEXT(DAY(Start_Date__c)) + &apos;/&apos; + TEXT(YEAR(Start_Date__c))</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Start Date Text</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Start_Date__c</fullName>
        <label>Start Date</label>
        <type>Date</type>
    </fields>
</CustomObject>

globalValueSets/Standard_Amperage.globalValueSet
<GlobalValueSet>
    <customValue>
        <fullName>8</fullName>
    </customValue>
    <customValue>
        <fullName>12</fullName>
    </customValue>
    <customValue>
        <fullName>15</fullName>
    </customValue>
    <customValue>
        <fullName>20</fullName>
    </customValue>
    <customValue>
        <fullName>25</fullName>
    </customValue>
    <customValue>
        <fullName>30</fullName>
    </customValue>
    <customValue>
        <fullName>32</fullName>
    </customValue>
    <customValue>
        <fullName>35</fullName>
    </customValue>
    <customValue>
        <fullName>40</fullName>
    </customValue>
    <customValue>
        <fullName>45</fullName>
    </customValue>
    <customValue>
        <fullName>50</fullName>
    </customValue>
    <customValue>
        <fullName>60</fullName>
    </customValue>
    <customValue>
        <fullName>70</fullName>
    </customValue>
    <customValue>
        <fullName>80</fullName>
    </customValue>
    <customValue>
        <fullName>90</fullName>
    </customValue>
    <customValue>
        <fullName>100</fullName>
    </customValue>
    <masterLabel>Standard Amperage</masterLabel>
</GlobalValueSet>

classes/geoTests.cls
@isTest
private class geoTests {

    @isTest static void test_method_one() {
        Kiosk__c k = new Kiosk__c(name='test',City__c='San Francisco',State__c='CA',Street_Address__c='155 De Haro St',Zip_Code__c='94103');
        k.Geolocation__Latitude__s = 37.768350000;
        k.Geolocation__Longitude__s = -122.401788000;
        insert k;
    }

    @isTest static void test_method_two() {
        
        account a = new account(name='test', ShippingStreet = '155 De Haro', ShippingCity ='San Francisco', ShippingState = 'CA', ShippingPostalCode = '94044');
        insert a;
        RecordType recordTypeRec = [SELECT id FROM RecordType WHERE Name = 'Site' AND sObjectType = 'Opportunity'][0];
        opportunity o = new opportunity(name='test',stagename='Test Opp',closedate= date.today(), AccountId = a.id, RecordTypeId = recordTypeRec.Id);
        insert o;
        Id pricebookId = Test.getStandardPricebookId();
        Quote q = new Quote(name='test',OpportunityId=o.id, Pricebook2Id=pricebookId);
        insert q;
        Kiosk__c k = new Kiosk__c(Network_Region__c = 'HI',name='test',City__c='Naytahwaush',State__c='GA',Street_Address__c='3150 Bright Shadow Impasse',Zip_Code__c='39996',Geolocation__Latitude__s=37.7655519,Geolocation__Longitude__s=-122.4000855, Status__c = 'Under Construction', Latitude__c = 37.7655519, Longitude__c = -122.4000855, Charging_Engineered_for__c = '12');
        insert k;
        Product2 p = new Product2(name='test',Kiosk__c=k.id);
        insert p;
        Product2 p3 = new Product2(name='test p3',Kiosk__c=k.id);
        insert p3;
        
        System.debug('Product p : ' + p.id);
        
        
        PricebookEntry standardPrice = new PricebookEntry(Pricebook2Id=pricebookId,Product2Id=p.Id,UnitPrice = 10000,IsActive=true);
        insert standardPrice;
        
        Asset ast = new Asset(AccountId=a.id,Name='test',InstallDate=Date.today(),UsageEndDate=date.today().addmonths(1),Product2Id=p.id, kiosk__c = k.id);
        insert ast;
        Asset ast1 = new Asset(AccountId=a.id,Name='test',InstallDate=Date.today().addmonths(1),UsageEndDate=date.today().addmonths(1).addDays(15),Product2Id=p.id, kiosk__c = k.id);
        insert ast1;
        Asset ast2 = new Asset(AccountId=a.id,Name='test',InstallDate=Date.today().addmonths(-2),UsageEndDate=date.today().addmonths(6),Product2Id=p.id, kiosk__c = k.id);
        insert ast2;
        Asset ast3 = new Asset(AccountId=a.id,Name='test',InstallDate=Date.today().addmonths(-2),UsageEndDate=date.today().addmonths(1),Product2Id=p.id, kiosk__c = k.id);
        insert ast3;
        Quote q1 = new Quote(name='test',OpportunityId=o.id,Pricebook2Id=pricebookId);
        insert q1;
        QuoteLineItem qli = new QuoteLineItem(Product2Id = p.id, PricebookEntryId=standardPrice.id,Quantity=1,QuoteId=q1.id,UnitPrice=10000,Start_Date__c=date.today().addmonths(1),End_Date__c=date.today().addmonths(2));
        insert qli;
        QuoteLineItem qli4 = new QuoteLineItem(Product2Id = p3.id, PricebookEntryId=standardPrice.id,Quantity=1,QuoteId=q1.id,UnitPrice=10000,Start_Date__c=date.today().addmonths(1),End_Date__c=date.today().addmonths(2));
        insert qli4;
        System.debug('Test qli : ' + qli);
        
        Kiosk__c k1 = new Kiosk__c(Network_Region__c = 'HI',name='test',City__c='Naytahwaush',State__c='GA',Street_Address__c='3150 Bright Shadow Impasse',Zip_Code__c='39996',Geolocation__Latitude__s=37.7655519,Geolocation__Longitude__s=-122.4000855, Status__c = 'Active', Latitude__c = 37.7655519, Longitude__c = -122.4000855);
        insert k1;
        Product2 p1 = new Product2(name='test',Kiosk__c=k1.id);
        insert p1;
        
        System.debug('Product p1 : ' + p1.id);
        
        PricebookEntry standardPrice1 = new PricebookEntry(Pricebook2Id=pricebookId,Product2Id=p1.Id,UnitPrice = 10000,IsActive=true);
        insert standardPrice1;
        
        QuoteLineItem qli2 = new QuoteLineItem(Product2Id = p1.id, PricebookEntryId=standardPrice.id,Quantity=1,QuoteId=q1.id,UnitPrice=10000,Start_Date__c=date.today().addmonths(1),End_Date__c=date.today().addmonths(2));
        insert qli2;
        QuoteLineItem qli3 = new QuoteLineItem(Product2Id = p1.id, PricebookEntryId=standardPrice.id,Quantity=3,QuoteId=q1.id,UnitPrice=10000,Start_Date__c=date.today().addmonths(1),End_Date__c=date.today().addmonths(2));
        insert qli3;
        System.debug('Test qli2 : ' + qli2);
        
        Date_Input__c dateInputRef = new Date_Input__c(SetupOwnerId=UserInfo.getProfileId(), Date_Field_1__c = date.today(), Date_Field_2__c = date.today().addmonths(3));
        insert dateInputRef;
        
        PageReference Page = new PageReference('/apex/MapPage?qid='+q.id);
        test.setcurrentpage(Page);
        System.currentPageReference().getParameters().put('id', q.id);
        MapClass mapC = new MapClass();
        //mapC.codeCoverage();
        mapC.choosePriceBook();
        mapC.qut.Pricebook2Id = pricebookId;
        mapC.choosePriceBook();
        mapC.qut.Start_Date_for_Map_Page__c = date.today();
        mapC.qut.End_Date_for_Map_Page__c = date.today().addmonths(2);
        mapC.regnPicked = 'HI';
        mapC.underConstruction = true;
        mapC.alreadyBooked = true;
        
        System.debug('Test : ' + [select id from Kiosk__c where Network_Region__c = :mapC.regnPicked AND Longitude__c != null AND Latitude__c != null AND Status__c != 'Under Construction']);
        
        mapC.updateSearch();
        list<string> stringList = new list<string>();
        stringList.add(p.id);
        stringList.add(p1.id);
        string st = System.now().addDays(-15).formatGMT('EEE MMM dd HH:mm:ss ZZZZ yyyy');
        string en = System.now().addMonths(4).formatGMT('EEE MMM dd HH:mm:ss ZZZZ yyyy');
        
        System.debug('st : ' + st + ',en : ' + en);
        //String st = '2018-08-01 00:00:00';
        //String en = '2018-12-30 00:00:00';
        //string st = mapC.startDateString;
        //string en = mapC.endDateString;
        System.debug('AssetList from test class : ' + [select Start_Date_Text__c,End_Date_Text__c,AccountId,Product2Id,UsageEndDate,InstallDate from Asset]);
        MapClass.addProducts(stringList, q.id, st, en);
        mapC.returnToQuote();
        mapC.qliToRemove = qli2.id;
        mapC.getExistingFaces();
        mapC.removeFromQuote();
    }

    @isTest(seealldata = true) static void test_method_three() {
        Kiosk__c k = [select Zip_Code__c from Kiosk__c where Zip_Code__c != null limit 1];
        string s = k.Zip_Code__c;
        k.Zip_Code__c = '10001';
        update k;
        
        account a = new account(name='test', ShippingStreet = '155 De Haro', ShippingCity ='San Francisco', ShippingState = 'CA', ShippingPostalCode = '94044');
        insert a;
        RecordType recordTypeRec = [SELECT id FROM RecordType WHERE Name = 'Site' AND sObjectType = 'Opportunity'][0];
        opportunity o = new opportunity(name='test',stagename='Test Opp',closedate= date.today(), AccountId = a.id, RecordTypeId = recordTypeRec.Id);
        insert o;
        
        Quote q = new Quote(name='test',OpportunityId=o.id);
        insert q;
        
        PageReference Page = new PageReference('/apex/MapPage?qid='+q.id);
        test.setcurrentpage(Page);
        System.currentPageReference().getParameters().put('id', q.id);
        MapClass mapC = new MapClass();
        mapC.choosePriceBook();
        
        
    }

    @isTest static void test_method_four() {
        account a = new account(name='test', ShippingStreet = '155 De Haro', ShippingCity ='San Francisco', ShippingState = 'CA', ShippingPostalCode = '94044');
        insert a;
        RecordType recordTypeRec = [SELECT id FROM RecordType WHERE Name = 'Site' AND sObjectType = 'Opportunity'][0];
        opportunity o = new opportunity(name='test',stagename='Test Opp',closedate= date.today(), AccountId = a.id, RecordTypeId = recordTypeRec.Id);
        insert o;
        Kiosk__c k = new Kiosk__c(Network_Region__c = 'HI',name='test',City__c='Naytahwaush',State__c='GA',Street_Address__c='3150 Bright Shadow Impasse',Zip_Code__c='39996',Geolocation__Latitude__s=37.7655519,Geolocation__Longitude__s=-122.4000855);
        insert k;
        Product2 p = new Product2(name='test',Kiosk__c=k.id);
        insert p;
        Id pricebookId = Test.getStandardPricebookId();
        PricebookEntry standardPrice = new PricebookEntry(Pricebook2Id=pricebookId,Product2Id=p.Id,UnitPrice = 10000,IsActive=true);
        insert standardPrice;
        Quote q = new Quote(name='test',OpportunityId=o.id,Pricebook2Id=pricebookId);
        insert q;
        QuoteLineItem qli = new QuoteLineItem(PricebookEntryId=standardPrice.id,Quantity=1,QuoteId=q.id,UnitPrice=10000);
        insert qli;
        qli.Quantity = 2;
        update qli;
        Profile pr = [select id from profile where name='Standard User'];
        User u = new User(firstname='test',lastname='test',email='thisisatestemail@asdfasdfasdfnigknekncih.com',username='thisisatestemail@asdfasdfasdfnigknekncih.com',alias='asdfasdf',TimeZoneSidKey='GMT',LocaleSidKey='en_US',emailencodingkey='UTF-8',languagelocalekey='en_US',ProfileId = pr.Id);
        insert u;
        opportunity o1 = new opportunity(name='test',stagename='Test Opp',closedate=date.today(),AccountId=a.id,ownerid=u.id, RecordTypeId = recordTypeRec.Id);
        insert o1;
        Quote q1 = new Quote(name='test',OpportunityId=o1.id,Pricebook2Id=pricebookId);
        insert q1;
        QuoteLineItem qli1 = new QuoteLineItem(PricebookEntryId=standardPrice.id,Quantity=1,QuoteId=q1.id,UnitPrice=10000);
        insert qli1;


        PageReference Page = new PageReference('/apex/ImageAttachment?id='+q.id);
        test.setcurrentpage(Page);
        ImageAttachment ia = new ImageAttachment(null);
        ia.runatstart();

    }

}